# -*- coding: utf-8 -*-
"""tamminimongodp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StTFnlJuLr177o5LSemfK2M8CNoX6e3j
"""


import streamlit as st
from pymongo import MongoClient
from datetime import datetime
import requests                      
from streamlit_lottie import st_lottie 


from pymongo import MongoClient




uri = "mongodb+srv://tammeni25:mentalhealth255@tamminicluster.nunk6nw.mongodb.net/?retryWrites=true&w=majority&authSource=admin"


client = MongoClient(uri)


db = client["tammini_db"]
users_col = db["users"]
responses_col = db["responses"]

# ----------------- Page Config -----------------
st.set_page_config(page_title="منصة طَمّني", layout="centered", page_icon="🧠")


def load_lottieurl(url):
    response = requests.get(url)
    if response.status_code != 200:
        return None
    return response.json()

# Load animation once for reuse
lottie_brain = load_lottieurl("https://assets4.lottiefiles.com/packages/lf20_4kx2q32n.json")


# ----------------- Landing Page -----------------
def show_landing_page():
    st.markdown("""
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap" rel="stylesheet">
        <style>
        html, body, .stApp {
            background-color: #e6f7ff;
            font-family: 'Cairo', sans-serif;
            direction: rtl;
        }
        .landing-container {
            text-align: center;
            padding: 30px;
            background-color: #ffffff;
            border-radius: 12px;
            margin-bottom: 30px;
        }
        h1 {
            color: #005b99;
            font-size: 36px;
        }
        h3 {
            color: #333333;
        }
        </style>
        <div class='landing-container'>
            <h1>مرحباً بك في منصة طَمّني</h1>
            <h3>لتقييم الصحة النفسية باستخدام الذكاء الاصطناعي</h3>
        </div>
    """, unsafe_allow_html=True)

    st_lottie(lottie_brain, height=250, speed=1)
    if st.button("تسجيل الدخول / إنشاء حساب"):
        st.session_state.page = "auth"

# ----------------- Auth -----------------

def signup():
    st.subheader("🔐 تسجيل حساب جديد")
    username = st.text_input("اسم المستخدم")
    password = st.text_input("كلمة المرور", type="password")
    if st.button("تسجيل"):
        existing_user = users_col.find_one({"username": username})
        if existing_user:
            st.warning("هذا المستخدم مسجل بالفعل. يتم عرض التقرير الأول:")
            
            # Fetch the earliest response
            existing_response = responses_col.find_one(
                {"username": username}, sort=[("timestamp", 1)]
            )
            
            if existing_response:
                st.markdown("### 🗂️ التقرير الأول للمستخدم:")
                st.write(f"👤 الجنس: {existing_response['gender']}")
                st.write(f"📅 العمر: {existing_response['age']}")
                for i in range(1, 7):
                    st.write(f"س{i}: {existing_response.get(f'q{i}', '')}")

                if "result" in existing_response:
                    st.success(f"✅ النتيجة المحللة: {existing_response['result']}")
                else:
                    st.info("📌 لم يتم تحليل النتيجة بعد من قبل النموذج.")
            else:
                st.info("🔍 لا توجد ردود محفوظة لهذا المستخدم.")
        else:
            users_col.insert_one({"username": username, "password": password})
            st.success("✅ تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.")




def login():
    st.subheader("🔑 تسجيل الدخول")
    username = st.text_input("اسم المستخدم")
    password = st.text_input("كلمة المرور", type="password")
    if st.button("دخول"):
        user = users_col.find_one({"username": username, "password": password})
        if user:
            st.session_state['user'] = username
            st.success("مرحباً بك، تم تسجيل الدخول.")
            
            # ✅ Show animation
            st_lottie(lottie_brain, height=250, speed=1, loop=False)
        else:
            st.error("بيانات الدخول غير صحيحة.")



# ----------------- Questionnaire -----------------

def questionnaire():
    st.subheader("📝 التقييم النفسي")
    gender = st.radio("ما هو جنسك؟", ["ذكر", "أنثى"])
    age = st.radio("ما هي فئتك العمرية؟", ["18-29", "30-39", "40-49", "50+"])

    q1_label = "س1: ھل تجد نفسك تعاني من التفكير المفرط أو القلق الزائد تجاه مختلف الأمور الحياتية المحيطة بك، سواء كانت متعلقة بالعمل، الدراسة، المنزل، أو غيرها من الجوانب اليومية؟ اعط أمثلة على بعض من هذه الأمور وكيف يؤثر التفكير والقلق بها على أفكارك وسلوكك خلال اليوم."
    q2_label = "س2: ھل تواجه صعوبة في السيطرة على أفكارك القلقة أو التحكم في مستوى القلق الذي تشعر به، بحيث تشعر أن الأمر خارج عن إرادتك أو أنه مستمر على نحو يرهقك؟ اجعل إجابتك تفصيلية بحيث توضح كيف يكون خارج عن ارادتك أو إلى أي مدى يرهقك."
    q3_label = "س3: ھل يترافق مع التفكير المفرط أو القلق المستمر ثلاثة أعراض أو أكثر من الأعراض التالية: الشعور بعدم الارتياح أو بضغط نفسي كبير، الإحساس بالتعب والإرهاق بسهولة، صعوبة واضحة في التركيز، الشعور بالعصبية الزائدة، شد عضلي مزمن، اضطرابات في النوم، وغيرها؟ اذكر كل عرض تعاني منه وهل يؤثر على مهامك اليومية مثل العمل أو الدراسة أو حياتك الاجتماعية؟ وكيف يؤثر عليك بشكل يومي؟"
    q4_label = "س4: ھل مررت بفترة استمرت أسبوعين أو أكثر كنت تعاني خلالها من خمسة أعراض أو أكثر مما يلي، مع ضرورة وجود عرض المزاج المكتئب أو فقدان الشغف والاهتمام؟ اذكر الأعراض التي عانيت منها بالتفصيل و كيف أثرت عليك؟"
    q5_label = "س5: ھل أدت الأعراض التي مررت بها إلى شعورك بضيق نفسي شديد أو إلى تعطيل واضح لقدرتك على أداء مهامك اليومية، سواء في حياتك الاجتماعية، الوظيفية، أو الشخصية؟ كيف لاحظت تأثير ذلك عليك وعلى تفاعلاتك مع من حولك؟"
    q6_label = "س6: ھل هذه الأعراض التي عانيت منها لم تكن ناتجة عن تأثير أي مواد مخدرة، أدوية معينة، أو بسبب حالة مرضية عضوية أخرى قد تكون أثرت على سلوكك أو مشاعرك خلال تلك الفترة؟"

    q1 = st.text_area(q1_label)
    q2 = st.text_area(q2_label)
    q3 = st.text_area(q3_label)
    q4 = st.text_area(q4_label)
    q5 = st.text_area(q5_label)
    q6 = st.text_area(q6_label)

    if st.button("إرسال التقييم"):
        answers = [q1, q2, q3, q4, q5, q6]

        if any(ans.strip() == "" for ans in answers):
            st.error("❗ الرجاء الإجابة على جميع الأسئلة.")
        elif any(any(char.isascii() and char.isalpha() for char in ans) for ans in answers):
            st.error("❗ الرجاء عدم استخدام أحرف إنجليزية في الإجابات.")
        else:
            user = st.session_state.get('user')
            if user:
                responses_col.insert_one({
                    "username": user,
                    "gender": gender,
                    "age": age,
                    "q1": q1,
                    "q2": q2,
                    "q3": q3,
                    "q4": q4,
                    "q5": q5,
                    "q6": q6,
                    "timestamp": datetime.now()
                })
                st.success("✅ تم حفظ الإجابات.")
            else:
                st.error("⚠️ يرجى تسجيل الدخول أولاً.")

# ----------------- Header -----------------

st.markdown("""
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap" rel="stylesheet">
    <style>
    html, body, .stApp {
        background-color: #e6f7ff;
        font-family: 'Cairo', sans-serif;
        direction: rtl;
    }
    .stButton>button {
        background-color: #66ccff;
        color: white;
        border-radius: 10px;
        font-size: 18px;
        padding: 10px 20px;
        border: none;
    }
    .stButton>button:hover {
        background-color: #4db8ff;
    }
    .stRadio>div {
        background-color: #f2fbff;
        padding: 10px;
        border-radius: 10px;
    }
    h1, h2, h3 {
        color: #005b99;
        text-align: center;
    }
    .title-container {
        background-color: #b3e0ff;
        padding: 30px;
        border-radius: 12px;
        margin-bottom: 30px;
    }
    </style>

    <div class='title-container'>
        <h1>طَمّني</h1>
        <h3>منصة تقييم الصحة النفسية باستخدام الذكاء الاصطناعي</h3>
      <img src='https://cdn-icons-png.flaticon.com/512/4320/4320337.png' width='90'/>

    </div>
""", unsafe_allow_html=True)

# ----------------- Navigation -----------------

if 'page' not in st.session_state:
    st.session_state.page = "landing"

if st.session_state.page == "landing":
    if st.button("تسجيل الدخول / إنشاء حساب"):

        st.session_state.page = "auth"
    st.stop()

if 'user' not in st.session_state:
    page = st.radio("اختر الصفحة", ["تسجيل الدخول", "تسجيل جديد"], horizontal=True)
    if page == "تسجيل الدخول":
        login()
    else:
        signup()
    st.stop()
else:
    questionnaire()

